# Generated by Django 4.2.7 on 2025-11-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('payment_received', 'Payment Received'), ('printing', 'Printing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='payment_received', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='template',
            field=models.CharField(choices=[('template1', 'Template 1 - Classic'), ('template2', 'Template 2 - Modern'), ('template3', 'Template 3 - Minimal'), ('template4', 'Template 4 - Elegant')], default='template1', max_length=20),
        ),
    ]
