# Generated by Django 4.2.7 on 2025-11-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_gallery_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_color',
            field=models.CharField(default='#E6E0F2', help_text='Card background color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='button_color',
            field=models.CharField(default='#1E3A8A', help_text='Button color (hex code)', max_length=7),
        ),
    ]
