# Generated by Django 4.2.7 on 2025-11-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_background_color_profile_button_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_color',
            field=models.CharField(default='#FFFFFF', help_text='Card background color (hex code or gradient)', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='background_color',
            field=models.CharField(default='#E6E0F2', help_text='Page background color (hex code or gradient)', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='button_color',
            field=models.CharField(default='#1E3A8A', help_text='Button color (hex code or gradient)', max_length=100),
        ),
    ]
