# Generated by Django 4.2.7 on 2025-11-05 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_card_color_alter_profile_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='figma',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
